server:
  servlet:
    context-path: /bookshelf

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookshelf_db?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: admin
    password: Qw123456
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  thymeleaf:
    cache: false